### ISSUE TITLE
Subscriptions crash due to JSON parsing error

### ISSUE THREAD

**Issue by lteacher** [lteacher/simple-fxtrade#20]
As mentioned in the comments for #17 the Oanda api sends multiple messages on some rare occasions separated by new line. This causes the stream to crash due to JSON parsing error:

```
SyntaxError: Unexpected token { in JSON at position 266
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/lteacher/simple-fxtrade/dist/node.js:7:31422)
    at emitOne (events.js:115:13)
    at IncomingMessage.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at IncomingMessage.Readable.push (_stream_readable.js:197:10)
    at HTTPParser.parserOnBody (_http_common.js:140:22)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
```

The issue happened after running for 6hrs but I think it just takes a while till it happens... dunno but important point is need to handle this.

**Comment by lteacher** [comment]
After running over 24hrs no issues or crashes.
